//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YtEzDL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YtEzDL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ContextAbout {
            get {
                return ResourceManager.GetString("ContextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture clipboard.
        /// </summary>
        internal static string ContextCaptureClipboard {
            get {
                return ResourceManager.GetString("ContextCaptureClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear cache.
        /// </summary>
        internal static string ContextClearCache {
            get {
                return ResourceManager.GetString("ContextClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ContextExit {
            get {
                return ResourceManager.GetString("ContextExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ContextSettings {
            get {
                return ResourceManager.GetString("ContextSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string ContextUpdate {
            get {
                return ResourceManager.GetString("ContextUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to written by worstenbrood (worstenbrood@gmail.com).
        /// </summary>
        internal static string EzYtDlCredits {
            get {
                return ResourceManager.GetString("EzYtDlCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ezytdl version: {0}.
        /// </summary>
        internal static string EzYtDlVersion {
            get {
                return ResourceManager.GetString("EzYtDlVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching {0}.
        /// </summary>
        internal static string Fetching {
            get {
                return ResourceManager.GetString("Fetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/FFmpeg/FFmpeg.
        /// </summary>
        internal static string FfMpegUrl {
            get {
                return ResourceManager.GetString("FfMpegUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/thielj/MetroFramework.
        /// </summary>
        internal static string MetroFrameworkUrl {
            get {
                return ResourceManager.GetString("MetroFrameworkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetroFramework version: {0}.
        /// </summary>
        internal static string MetroFrameworkVersion {
            get {
                return ResourceManager.GetString("MetroFrameworkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist: {0} ({1}).
        /// </summary>
        internal static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing cache.
        /// </summary>
        internal static string RemoveCacheError {
            get {
                return ResourceManager.GetString("RemoveCacheError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding metadata ....
        /// </summary>
        internal static string StatusAddingMetadata {
            get {
                return ResourceManager.GetString("StatusAddingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting ....
        /// </summary>
        internal static string StatusConverting {
            get {
                return ResourceManager.GetString("StatusConverting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting thumbnail ....
        /// </summary>
        internal static string StatusConvertingThumbnail {
            get {
                return ResourceManager.GetString("StatusConvertingThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting video ....
        /// </summary>
        internal static string StatusConvertingVideo {
            get {
                return ResourceManager.GetString("StatusConvertingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string StatusDone {
            get {
                return ResourceManager.GetString("StatusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedding thumbnail ....
        /// </summary>
        internal static string StatusEmbeddingThumbnail {
            get {
                return ResourceManager.GetString("StatusEmbeddingThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting audio ....
        /// </summary>
        internal static string StatusExtractingAudio {
            get {
                return ResourceManager.GetString("StatusExtractingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0} / Selected: {1}.
        /// </summary>
        internal static string StatusLabelText {
            get {
                return ResourceManager.GetString("StatusLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System exception.
        /// </summary>
        internal static string SystemException {
            get {
                return ResourceManager.GetString("SystemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track: {0} ({1}).
        /// </summary>
        internal static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://chromium.googlesource.com/webm/libwebp.
        /// </summary>
        internal static string WebPUrl {
            get {
                return ResourceManager.GetString("WebPUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebP version: {0}.
        /// </summary>
        internal static string WebPVersion {
            get {
                return ResourceManager.GetString("WebPVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/JosePineiro/WebP-wrapper.
        /// </summary>
        internal static string WebPWrapperUrl {
            get {
                return ResourceManager.GetString("WebPWrapperUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yt-dlp.
        /// </summary>
        internal static string YtDlp {
            get {
                return ResourceManager.GetString("YtDlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yt-dlp error.
        /// </summary>
        internal static string YtDlpError {
            get {
                return ResourceManager.GetString("YtDlpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yt-dlp update.
        /// </summary>
        internal static string YtDlpUpdate {
            get {
                return ResourceManager.GetString("YtDlpUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/yt-dlp/yt-dlp.
        /// </summary>
        internal static string YtDlpUrl {
            get {
                return ResourceManager.GetString("YtDlpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yt-dlp version: {0}.
        /// </summary>
        internal static string YtDlpVersion {
            get {
                return ResourceManager.GetString("YtDlpVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon YTIcon {
            get {
                object obj = ResourceManager.GetObject("YTIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
